package gui;


import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import models.TransfersTableModel;
import models.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.table.TableCellRenderer;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Mariana
 */
public class UserInterface extends JFrame {
	private static final long serialVersionUID = 1L;
	UIMediator uiMediator;
    /**
     * Creates new form GUI
     */
    public UserInterface(UIMediator uiMediator) {
        this.uiMediator = uiMediator;
        this.uiMediator.registerUserInterface(this);
        initComponents();

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AutoGeneratedGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AutoGeneratedGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AutoGeneratedGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AutoGeneratedGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initComponents() {

        statusLabel = new JLabel();
        mainSplitPane = new JSplitPane();
        leftSplitPane = new JSplitPane();
        filesScrollPane = new JScrollPane();
        filesList = new JTree();
        transfersScrollPane = new JScrollPane();
        transfersTable = new JTable();
        usersScrollPane = new JScrollPane();
        usersList = new UserList(uiMediator);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setTitle("Welcome - " + this.uiMediator.getUsername());

        statusLabel.setText("");
        uiMediator.registerStatusLabel(statusLabel);

        mainSplitPane.setDividerLocation(480);
        mainSplitPane.setResizeWeight(1.0);

        leftSplitPane.setDividerLocation(200);
        leftSplitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);
        leftSplitPane.setResizeWeight(0.5);

        filesList.setModel(new UserFilesTreeModel(null, uiMediator));
        filesList.getSelectionModel().setSelectionMode
                (TreeSelectionModel.SINGLE_TREE_SELECTION);
        filesList.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                        filesList.getLastSelectedPathComponent();
                if (node == null)
                    return;
                 if (e.getClickCount() == 2 && !e.isConsumed()) {
                     e.consume();
                     String path = "";
                     for(TreeNode tn : node.getPath())
                        path += tn.toString() + "/";
                     path = path.substring(0, path.length() - 1);
                     if(node.isLeaf()) {
                         uiMediator.newIncomingTransfer(path);
                     }
                 }
             }
         });
        filesScrollPane.setViewportView(filesList);

        leftSplitPane.setLeftComponent(filesScrollPane);

        transfersTable.setModel(new TransfersTableModel(uiMediator));
        transfersTable.setDefaultRenderer(JProgressBar.class,
                new TableCellRenderer() {
                        @Override
                        public Component getTableCellRendererComponent(
                                JTable table, Object value, boolean isSelected,
                                boolean hasFocus, int row, int column) {
                            return (JProgressBar) value;
                        }
                });
        transfersScrollPane.setViewportView(transfersTable);

        leftSplitPane.setRightComponent(transfersScrollPane);

        mainSplitPane.setLeftComponent(leftSplitPane);

        usersList.setModel(new UserListModel(uiMediator));
        usersScrollPane.setViewportView(usersList);

        mainSplitPane.setRightComponent(usersScrollPane);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(mainSplitPane, GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSplitPane, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel))
        );

        pack();
    }

    // Variables declaration - do not modify
    private JTree filesList;
    private JScrollPane filesScrollPane;
    private JSplitPane leftSplitPane;
    private JSplitPane mainSplitPane;
    private JLabel statusLabel;
    private JScrollPane transfersScrollPane;
    private JTable transfersTable;
    private JList<String> usersList;
    private JScrollPane usersScrollPane;
    // End of variables declaration
}
